server:
  port: 7000

spring:
  application:
    name: eureka-service
  security:
    user:
      #认证信息
      name: mujio
      password: 123456

eureka:
  client:
    #是否注册到Eureka服务中
    register-with-eureka: true
    #是否从Eureka服务中获取注册信息
    fetch-registry: false
    service-url:
      #Eureka客户端与服务端进行交互的地址,加入认证信息
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:${server.port}/eureka/