server:
  port: 7002

spring:
  application:
    name: eureka-server
  security:
    user:
      #认证信息
      name: mujio
      password: 123456

eureka:
  client:
    #是否注册到Eureka服务中
    register-with-eureka: true
    #是否从Eureka服务中获取注册信息---修改为true
    fetch-registry: true
    service-url:
      #Eureka客户端与服务端进行交互的地址,加入认证信息---修改为用","隔开的两个eureka地址
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:7000/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@localhost:7001/eureka/